DATA ENGINA;
LENGTH RESPONSE 12;
INPUT TREATMENT$ RESPONSE$ COUNT;
DATALINES;
TIMBOLO	NO ANGINA	44
PLACEBO	NO ANGINA	19
TIMBOLO ANGINA		116
PLACEBO	ANGINA		128
;
PROC FREQ DATA=ENGINA ORDER=DATA;
TABLES RESPONSE*TREATMENT/
		CHISQ DEVIATION 
		NOCOL NOROW;
WEIGHT COUNT;
RUN;
