DATA BETTLE;
INPUT CS KILLED;

DATALINES;
50 11
54 13
58 18
62 23
66 43
70 53
74 57
78 60
;
SYMBOL VALUE = circle I = none;
Proc gplot data = BETTLE;
plot CS*KILLED;
run;

PROC Nlin;
PARAMETERS K=60 Yo=0.01 R=0.01 TO 0.5 by 0.15;
MODEL KILLED = K/(1+((K-Yo)/Yo)*exp(-r*cs));
OUTPUT OUT=BETTLE_KILLED P=PREDY R=PREDR;
RUN;
QUIT;

PROC GPLOT DATA=BETTLE_KILLED;*PREDICTED;
PLOT 	CS*KILLED = 1
		PREDY*KILLED = 2/overlay;
run; 

PROC GPLOT DATA=BETTLE_KILLED;*RESIDUALS;
PLOT PREDR*KILLED/VREF=0;
RUN;

