DATA ODDS;
INPUT OUTCOME$ EXPOSURE$ COUNT;
DATALINES;
SICK YES 72
SICK NO 15
NO_SICK YES 84
NO_SICK NO 129 
;
PROC FREQ DATA=ODDS ORDER=DATA;
TABLES OUTCOME*EXPOSURE/ CHISQ CMH;
WEIGHT COUNT; 
RUN;
