DATA ASSIGN;
DO SUBJ=1 TO 10000;
	VARI = 10 + 1.2 * RANNOR(10); *GENERATES A DISTRIBUTION WITH AN MEAN=10 AND STD=1.2;
	OUTPUT;
END;
RUN;
PROC univariate;
HISTOGRAM VARI /NORMAL;
RUN;
/*
	VARI=RANNOR(10) -> Z-SCORE

	Z=(Y-MU)/SIGMA
	
	Y=MU -(SIGMA)(Z)
*/
